sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
cache:
  yarn: true
before_install:
  - yarn global add codecov
script:
  - yarn test -- --coverage
  - codecov
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
